author = "Joseph Bryn Wilson"
date = "April 2, 2019"
description = "If you haven’t already seen it, Valve News Network uploaded a fantastic video covering Boreal Alyph, complete with some exciting new information."
link = "https://medium.com/keep-away-from-fire/the-engine-license-426fcd6d15a3"
title = "THE ENGINE LICENSE"