author = "Joseph Bryn Wilson"
date = "December 25, 2019"
description = "Merry Christmas and a Happy Holidays, everyone! Keep Away From Fire is back for Kaffmas, this time bringing a little something from White Forest — a Christmas card!"
link = "https://medium.com/keep-away-from-fire/kaffmas-2019-faeecc23ab19"
title = "KAFFMAS 2019"