author = "Joseph Bryn Wilson"
date = "December 25, 2018"
description = "We hope you’re not completely turned off by the presumptuous title, but either way, happy holidays from the Keep Away from Fire team!"
link = "https://medium.com/@jbwilson427/827ae95ac5ae"
title = "KAFFMAS 2018"