author = "Joseph Bryn Wilson"
date = "November 19, 2018"
description = "It’s been quite a while since our last update. In the meantime, we’ve significantly re-structured and re-organised our team."
link = "https://medium.com/keep-away-from-fire/boreal-alyph-update-november-2018-16e7a15f0678"
title = "BOREAL ALYPH UPDATE: NOVEMBER 2018"