author = "Joseph Bryn Wilson"
date = "October 26, 2019"
description = "Boreal Alyph has a new update to share, albeit small. No need to panic, though, as the full update is set for January"
link = "https://medium.com/keep-away-from-fire/boreal-alyph-mini-update-october-2019-b278a6690eeb"
title = "BOREAL ALYPH MINI UPDATE: OCTOBER 2019"