name = ""

nickname = "EmNudge"

position = "Voice Acting"

img = "nudge.png"

bio = "Voice actor, web developer, and water enthusiast. <br/><br/>Special talents include Mongolian throat singing and counting to 5 using all 10 fingers."

[[links]]
name = "Website"
url = "https://emnudge.com"

[[links]]
name = "Steam"
url = "https://steamcommunity.com/id/eMnudge/"

[[links]]
name = "Twitter"
url = "https://twitter.com/emnudge/"
