name = "Joseph Wilson"

nickname = "r0ckittman"

position = "PR"

img = "joseph.jpg"

bio = "An Australian writer, musician, and all-round content creator who can't tell if he should keep the word 'aspiring' next to any of his talents."

[[links]]
name = "Twitter"
url = "https://twitter.com/r0ckittman"

[[links]]
name = "Soundcloud"
url = "https://soundcloud.com/r0ckittman"