name = "Roxy Mason"

nickname = "Nukedrabbit95"

position = "Dev"

img = "nukedrabbit95.png"

bio = "In addition to helping lead Level Design and fighting weasel uprisings, she also does Programming, Sound Design, Writing, Composing, and whatever else she feels like at the moment."

[[links]]
name = "Steam"
url = "https://steamcommunity.com/id/nukedrabbit95/"

[[links]]
name = "Soundcloud"
url = "https://soundcloud.com/nukedrabbit95"