question = "Why is the team using Source and not [insert modern engine here]?"

answer = "We want Boreal Alyph to feel like it belongs in the episodic series. Moving to another engine would make that more difficult to do so."