question = "Will Boreal Alyph have [Insert beta concept]?"

answer = "We always take beta concepts into account and use them for inspiration, but will not be including any beta concepts just because it's a beta concept. We know about the beta, you don't need to ask."